\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename pretest.info
@settitle PreTest CookBook 0.1
@c %**end of header

@setchapternewpage odd

@ifinfo
PreTest CookBook

Copyright @copyright{} 2014 Assaf Gordon (agn@@gnu.org).
@end ifinfo

@titlepage
@sp 10
@comment The title is printed in a large font.
@center @titlefont{PreTest CookBook}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2014 Assaf Gordon (agn@@gnu.org)
@end titlepage

@node    Top,       Introduction, (dir),    (dir)
@comment node-name, next,          previous, up

@menu
* Introduction::         What this Pretest is all aobut
* Getting Started::      Using PreTest images
* Usage::                Effective use of these VMs
* Build Recipes::        How each VM was built
* Future Improvements::  The TODO List
* Concept Index::        The Index
@end menu

@contents

@c ***********************************************************
@c Introduction
@c ***********************************************************
@node    Introduction, Getting Started, Top,      Top
@comment node-name,     next,          previous, up
@chapter Introduction
@cindex Introduction

@c ***********************************************************
@c Getting Started
@c ***********************************************************
@node    Getting Started, Usage, Introduction,      Top
@comment node-name,     next,          previous, up
@chapter Getting Started
@cindex Getting Started

@c ***********************************************************
@c Usage
@c ***********************************************************
@node    Usage, Build Recipes, Getting Started, Top
@comment node-name,     next,          previous, up
@chapter Usage
@cindex Usage

@c ***********************************************************
@c Build Recipces
@c ***********************************************************
@node    Build Recipes, Future Improvements, Usage, Top
@comment node-name,     next,          previous, up
@chapter Build Recipes
@cindex Build Recipes

@c ***********************************************************
@c Future Improvements
@c ***********************************************************
@node Future Improvements, Concept Index, Build Recipes, Top
@chapter Future Improvements
@cindex Future Improvements

@section Scripts

Check mimimum version of QEMU/KVM (missing @option{-q} on old @command{qemu-img}).

@section Guest VMs

CloudInit/KickStart automation - passing commands to guest (perhaps with iso)

Communicate with host when boot process is done, and login through SSH is possible.

Add "-serial file:" device (as second serial port), allow dumping data from guest to host
without network.

Fix NetBSD (boot withot -no-kvm on Debian7), fix /root/.profile 's invalid export command

@verbatim
Multiple-Serials:
http://lists.gnu.org/archive/html/qemu-devel/2010-01/msg00458.html
    -nodefaults \
    -vga std \
    -serial mon:stdio \
    -serial file:"$NAME.booted" \
    -serial file:"$NAME.par"
@end verbatim


New run script which waits until the system has booted (with daemon,pid,ssh access).

MOTD in each VM, pointing back to PreTest

@section Manual

Root passwod exception: minix,hurd (no password)

Sudo: minix

@node    Concept Index,    ,  Future Improvements, Top
@comment node-name,    next,  previous,      up
@unnumbered Concept Index

@printindex cp

@bye

